worker_rlimit_nofile 65535;

events {
    worker_connections  20480; # Default 1024 hota hai, isko badha ke 20480 karo
    multi_accept on;
}

http {
    upstream backend_servers {
        least_conn; # Ya round-robin
        server host.docker.internal:8000; # server 1
        server host.docker.internal:8001; # server 2
        
        keepalive 128; # Upstream connection reuse
    }

    server {
        listen 80; # Ya tera configured nginx port

        location / {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Timeouts badhao taaki burst drop na ho
            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}
